import type { Project } from "./types";

export const ABBREVIATIONS: Record<string, string> = {
  "PO & ABOQ": "Purchase Order & As-built Bill of Qty",
  "PAT": "Preliminary Acceptance Test",
  "RFS": "Ready for Service",
  "PAC": "Provisional Acceptance Certificate",
  "PCR & SDN": "PURCHASE CHANGE REQUEST & Service Delivery Note",
  "FAC": "Final Acceptance Certificate",
  "GIS": "Geographic Information System",
  "CRQ HO": "Change Request Hand Over",
};

export function getAbbreviation(label: string): string | null {
  for (const abbr of Object.keys(ABBREVIATIONS)) {
    if (label.includes(abbr)) return ABBREVIATIONS[abbr];
  }
  return null;
}

export const DEMO_PROJECT: Project = {
  id: "demo-project-0000-0000-0000-000000000000",
  owner_id: "guest",
  project_name: "Demo Project — Riyadh FTTH Expansion",
  po_number: "PO-DEMO-2026-001",
  plan_no: "PLN-RUH-0042",
  po_value_sar: 1250000,
  site_id: "RUH-N-0042",
  region: "Central Region",
  city: "Riyadh",
  sector: "North District",
  project_type: "FTTH",
  latitude: 24.7136,
  longitude: 46.6753,
  sn: "DEMO-001",
  status: "In Progress",
  created_at: new Date().toISOString(),
  stage1: {
    surveyStatus: "approved",
    designStatus: "approved",
    dboqStatus: "approved",
    dboqAmount: 1250000,
    sendDocsDate: "2026-01-15",
    receiveDocsDate: "2026-01-20",
    planNo: "PLN-RUH-0042",
  },
  stage2: {
    poReceiveStatus: "approved",
    aboqStatus: "approved",
    aboqAmount: 1250000,
    poAmount: 1250000,
    baselineStartDate: "2026-02-01",
    baselineEndDate: "2026-06-30",
    aboqSubmittedDate: "2026-01-25",
    aboqApprovedDate: "2026-02-01",
    poIssuanceDate: "2026-01-28",
    sendDocsDate: "",
    receiveDocsDate: "",
  },
  stage3: {
    permitsStatus: "approved",
    civilActualMeters: 4200,
    hddActualMeters: 850,
    mhHh: 24,
    odbOdf: 36,
    closures: 18,
    fiberCableMeters: 5050,
    fiberSplicingStatus: "approved",
    patchingStatus: "inprogress",
    patchingDoneStatus: "inprogress",
    civilStatus: "approved",
    actualStartDate: "2026-02-05",
    actualEndDate: "2026-04-15",
    closePermit: "submitted",
    clearancePermit: "pending",
    permitSubmittedDate: "2026-01-28",
    permitIssuedDate: "2026-02-03",
    permitClosedDate: "2026-04-20",
    permitClearancedDate: "",
    finalClearanceStatus: "pending",
  },
  stage4: {
    patStatus: "submitted",
    patReqNo: "PAT-2026-0042",
    owsPatRequestDate: "2026-04-20",
    patStartDate: "2026-04-25",
    patStage: "Projects Team",
    gisStatus: "approved",
    gisDocsSentDate: "2026-04-18",
    gisReceivedDate: "2026-04-22",
    crqHoStatus: "pending",
    crqHoNo: "",
    crqHoErqNo: "",
    crqHoReqNo: "",
    crqHoSubmittedFilesDate: "",
    repatStatus: "inprogress",
    repatSubmittedFilesDate: "2026-05-01",
    repatReqNo: "RP-2026-0042",
    repatStage: "Operations Team",
    repatDate: "",
  },
  stage5: {
    pcrStatus: "inprogress",
    pcrRef: "PCR-2026-0042",
    pcrDate: "2026-05-10",
    sdnStatus: "pending",
    sdnDate: "",
    sdnRef: "",
    rfsStatus: "pending",
    rfsDate: "",
    rfsSubmittedFilesDate: "",
    rfsAmount: 1000000,
    pacStatus: "pending",
    pacCrqStatus: "pending",
    pacDate: "",
    pacSubmitFilesDate: "",
    pacCrqNo: "",
    pacErqNo: "",
    pacAmount: 125000,
  },
  stage6: {
    facStatus: "pending",
    facCrqStatus: "pending",
    facDate: "",
    facSubmitFilesDate: "",
    facAmount: 125000,
    clearancePermit: "pending",
    facCrqNo: "",
    facCrqErqNo: "",
    facReqNo: "",
    finalClearanceStatus: "pending",
  },
};
